import { PageIntro } from "@/components/PageIntro";
import { images } from "@/data/content";

const values = [["Faith", "God's Word is the foundation for all true healing."], ["Family", "Even imperfect families can build lasting legacies."], ["Simplicity", "Transformation is found in God's simple plan for life."], ["Community", "We grow stronger when we grow together."]];

export default function About() {
  return <>
    <PageIntro eyebrow="About us" title="From brokenness to a family legacy.">You do not need a perfect past to leave a powerful future.</PageIntro>
    <section className="section paper"><div className="container grid items-center gap-12 md:grid-cols-[.8fr_1fr]"><img src={images.author} alt="Gina Jenkins, founder of Lifetime Lifestyle" className="aspect-[4/5] w-full max-w-md rounded-[40%_40%_24px_24px] object-cover" /><div><p className="eyebrow !text-[var(--blue)]">Gina Jenkins · CEO & founder</p><h2 className="serif mt-4 text-4xl font-bold">Our family story became our mission.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Lifetime Lifestyle was born out of personal experience—struggles, setbacks, and breakthroughs that led to lasting transformation. What began as one family&apos;s journey to health and healing has grown into a mission to help others discover the same freedom.</p><p className="mt-5 text-lg leading-8 text-slate-600">Through moving to the countryside, growing food, exercising, and simplifying life, Gina discovered the timeless platform of God&apos;s Healthy Laws. These principles changed her body, her mind, and her faith—and now they are the heartbeat of everything we do.</p></div></div></section>
    <section className="section bg-[#05698e] text-white"><div className="container"><div className="mx-auto max-w-2xl text-center"><p className="font-montserrat text-sm font-bold uppercase tracking-[.22em] text-[var(--yellow)]">What guides us</p><h2 className="serif mt-4 text-5xl font-bold text-white">The simple things matter.</h2></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([title, body]) => <div key={title} className="rounded-[26px] bg-white p-7 text-[var(--ink)]"><span className="text-3xl text-[#05698e]">✦</span><h3 className="serif mt-5 text-2xl font-bold">{title}</h3><p className="mt-3 text-base leading-7 text-slate-600">{body}</p></div>)}</div></div></section>
    <section className="section paper"><div className="container grid gap-10 md:grid-cols-2"><div><p className="eyebrow !text-[var(--blue)]">Mission</p><h2 className="serif mt-3 text-4xl font-bold">Helping families rise into transformation.</h2><p className="mt-4 text-lg leading-8 text-slate-600">To help families—no matter their starting point—discover how God&apos;s Healthy Laws can transform their lives and establish a family legacy of health and faith for generations to come.</p></div><div><p className="eyebrow !text-[var(--blue)]">Vision</p><h2 className="serif mt-3 text-4xl font-bold">Health and hope for generations.</h2><p className="mt-4 text-lg leading-8 text-slate-600">To see families around the world rise from imperfection into transformation, proving that God&apos;s plan can turn weakness into strength.</p></div></div></section>
  </>;
}
