"use client";
import { FormEvent, useState } from "react";
import { PageBanner } from "@/components/PageBanner";

export default function Contact() {
  const [sent, setSent] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; await fetch("/api/contact", { method: "POST", body: new FormData(form) }); setSent(true); }
  return <><PageBanner eyebrow="Connect" title="We would love to hear from you.">Have a question about our books, programs, or resources? Send us a message.</PageBanner><section className="section paper"><div className="container grid gap-14 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow !text-[var(--blue)]">Contact us</p><h2 className="serif mt-4 text-5xl font-bold">Let&apos;s grow healthier together.</h2><p className="mt-6 leading-8">Reach out and our team will get back to you as soon as possible.</p><p className="mt-8 text-sm leading-7"><strong>Phone</strong><br />+1 918-658-9557<br /><br /><strong>Email</strong><br /><a className="text-[var(--blue)] underline" href="mailto:lifetimelifestylellc@gmail.com">lifetimelifestylellc@gmail.com</a></p></div><div className="bg-[var(--navy)] p-8 md:p-12">{sent ? <div className="py-16 text-center text-white"><p className="eyebrow">Message received</p><h3 className="serif mt-4 text-4xl font-bold">Thank you for reaching out.</h3></div> : <form onSubmit={submit} className="grid gap-5"><label className="grid gap-2 text-sm font-bold text-white">Name<input name="name" required className="border-b border-white/50 bg-transparent px-0 py-3 font-normal text-white outline-none" /></label><label className="grid gap-2 text-sm font-bold text-white">Email<input name="email" required type="email" className="border-b border-white/50 bg-transparent px-0 py-3 font-normal text-white outline-none" /></label><label className="grid gap-2 text-sm font-bold text-white">Message<textarea name="message" required rows={5} className="resize-none border-b border-white/50 bg-transparent px-0 py-3 font-normal text-white outline-none" /></label><button className="button mt-3 w-fit">Send message</button></form>}</div></div></section></>;
}
